export {default as Home} from './Home'
export {default as Posts} from './Posts'
export {default as Post} from './Post'
export {default as NotFound} from './NotFound'
export {default as About} from './About'
export {default as Login} from './Login'
export {default as Landing} from './Landing'